ALTERNATE_DRIVING_DIRECTION: 'false'
BOT_CAR_SPEED: '0.2'
CHANGE_START_POSITION: 'false'
ENABLE_DOMAIN_RANDOMIZATION: 'false'
IS_LANE_CHANGE: 'false'
IS_OBSTACLE_BOT_CAR: 'false'
LANE_CHANGE_DISTANCE: '1.0'
LOWER_LANE_CHANGE_TIME: '3.0'
MIN_DISTANCE_BETWEEN_BOT_CARS: '2.0'
NUMBER_OF_BOT_CARS: 3
NUMBER_OF_OBSTACLES: 0
RANDOMIZE_BOT_CAR_LOCATIONS: 'true'
RANDOMIZE_OBSTACLE_LOCATIONS: 'true'
UPPER_LANE_CHANGE_TIME: '5.0'
WORLD_NAME: reInvent2019_wide
